image: bradrydzewski/python:2.7
script:
  - pip install -r requirements.txt --use-mirrors
  - python svdn_djangular/manage.py test
notify:
  email:
    recipients:
      - svedin.erik@gmail.com
      - erik.svedin@willandskill.se
